name: DefenceTowers
version: '${project.version}'
main: me.isaac.defencetowers.DefenceTowersMain
api-version: 1.17
authors: [ IsaacTwinkleToes ]
website: https://github.com/NotIsaacTwinkleToes/DefenceTowers
commands:
  defencetowers:
    description: DefenceTowers Commands
    usage: /defencetowers
    permission: defencetowers.admin
    aliases: [dt]
